apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rag9-sep12-1 
  description: Secure Supply Chain Example for RAG Chatbot Application example with an LLM and a Vector database enabled   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=rag9-sep12-1  
    janus-idp.io/tekton: rag9-sep12-1 
    backstage.io/kubernetes-id: rag9-sep12-1 
    backstage.io/techdocs-ref: dir:. 
    quay.io/repository-slug: maysunfaisal/rag9-sep12-1
  tags: ["ai", "llamacpp", "vllm", "python", "rag", "database"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 